server:
  port: 8001
  servlet:
    context-path: /love
spring:
  application:
    name: sayportservice    #微服务名称
  cloud:
    consul:
      host: 192.168.254.130 #consul服务器地址
      port: 8500
      discovery:
        register: true            #是否注册到consul中
        hostname: 10.39.4.65   #服务端ip地址
        serviceName: ${spring.application.name}
        # 指定consul调用actuator提供的健康检查的路径
        health-check-path: /love/actuator/health
        # 健康检查的频率
        health-check-interval: 30s
        #微服务下的实例名称,一个微服务可以有多个实例提供负载均衡
        instanceId: provider8001
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_consul
    driver-class-name: com.mysql.jdbc.Driver