server:
  port: 81

sayportservice:
  ribbon:
    # 基于配置文件形式的针对单个服务的Ribbon负载均衡策略,经测试有用
    # NFLoadBalancerRuleClassName放在全局中无效!!!
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    #ReadTimeout也有效,能覆盖全局
    ReadTimeout: 1000



ribbon:
  MaxAutoRetriesNextServer: 0 #不允许调用另一个服务实例去重试
  MaxAutoRetries: 1 #服务挂了和服务超时都会重试
  ReadTimeout: 5000
  OkToRetryOnAllOperations: true

spring:
  application:
    name: consumer-81
  cloud:
    consul:
      host: 192.168.247.130 #consul地址
      port: 8500
      discovery:
        register: false #设置不需要注册到consul中

feign:
  hystrix:
    enabled: true #springcloud默认不开启hystrix功能




hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000 #hystrix的超时时间(ms)
      circuitBreaker:
        requestVolumeThreshold: 20