server:
  port: 81

ribbon:
  MaxAutoRetriesNextServer: 0 #不允许调用另一个服务实例去重试
  MaxAutoRetries: 1
  ReadTimeout: 15000

spring:
  application:
    name: consumer-81
  cloud:
    consul:
      host: 192.168.247.130 #consul地址
      port: 8500
      discovery:
        register: false #设置不需要注册到consul中
